info:
  author: "Linitly"
  version: @version@
  title: "Linitly Boot Frame Project"
  description: "Linitly Boot Frame Project API Doc"

server:
  port: 8081
  servlet:
    context-path: /@artifactId@
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linitly_boot?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useAffectedRows=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5                     #连接池初始大小
      min-idle: 5                         #连接池中最小的活跃连接数
      max-active: 20                      #连接池中最大的活跃连接数
      max-wait: 60000                     #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    host: localhost
    port: 6379
    password:
  jackson:
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      file-size-threshold: 10MB
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler             #调度器实例名称
            instanceId: AUTO                          #调度器实例编号自动生成
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool  #线程池实现类
            threadCount: 5                            #执行最大并发线程数量
            threadPriority: 5                         #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true    #配置是否启动自动加载数据库内的定时任务，默认true
    job-store-type: jdbc
#    jdbc:
#      initialize-schema: always
  elasticsearch:
    rest:
      username: elastic
      password: linitly
      uris:
        - http://115.159.42.127:9200
        - http://42.192.50.57:9200
        - http://122.51.251.122:9200
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/study-springboot

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:log/logback-spring.xml